// Code generated by ogen, DO NOT EDIT.

package v1

// setDefaults set default value of fields.
func (s *ListExecutionHistoryOK) setDefaults() {
	{
		val := int(0)
		s.Total = val
	}
	{
		val := int(0)
		s.From = val
	}
	{
		val := int(0)
		s.Count = val
	}
}

// setDefaults set default value of fields.
func (s *ListExecutionOK) setDefaults() {
	{
		val := int(0)
		s.Total = val
	}
	{
		val := int(0)
		s.From = val
	}
	{
		val := int(0)
		s.Count = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowOK) setDefaults() {
	{
		val := int(0)
		s.Total = val
	}
	{
		val := int(0)
		s.From = val
	}
	{
		val := int(0)
		s.Count = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowRevisionsOK) setDefaults() {
	{
		val := int(0)
		s.Total = val
	}
	{
		val := int(0)
		s.From = val
	}
	{
		val := int(0)
		s.Count = val
	}
}
