// Code generated by ogen, DO NOT EDIT.

package v1

// CancelExecutionParams is parameters of cancelExecution operation.
type CancelExecutionParams struct {
	// Workflow ID.
	ID string
	// Execution ID.
	ExecutionId string
}

// CreateExecutionParams is parameters of createExecution operation.
type CreateExecutionParams struct {
	// Workflow ID.
	ID string
}

// CreateWorkflowRevisionParams is parameters of createWorkflowRevision operation.
type CreateWorkflowRevisionParams struct {
	// Workflow ID.
	ID string
}

// DeleteExecutionParams is parameters of deleteExecution operation.
type DeleteExecutionParams struct {
	// Workflow ID.
	ID string
	// Execution ID.
	ExecutionId string
}

// DeleteWorkflowParams is parameters of deleteWorkflow operation.
type DeleteWorkflowParams struct {
	// Workflow ID.
	ID string
}

// DeleteWorkflowRevisionAliasParams is parameters of deleteWorkflowRevisionAlias operation.
type DeleteWorkflowRevisionAliasParams struct {
	// Workflow ID.
	ID string
	// Revision ID.
	RevisionId float64
}

// GetExecutionParams is parameters of getExecution operation.
type GetExecutionParams struct {
	// Workflow ID.
	ID string
	// Execution ID.
	ExecutionId string
}

// GetWorkflowParams is parameters of getWorkflow operation.
type GetWorkflowParams struct {
	// Workflow ID.
	ID string
}

// GetWorkflowRevisionsParams is parameters of getWorkflowRevisions operation.
type GetWorkflowRevisionsParams struct {
	// Workflow ID.
	ID string
	// Revision ID.
	RevisionId float64
}

// ListExecutionParams is parameters of listExecution operation.
type ListExecutionParams struct {
	// ページ番号.
	Page OptInt `json:",omitempty,omitzero"`
	// 1ページあたりのリソースの取得数.
	PageLimit OptInt `json:",omitempty,omitzero"`
	// ソートの順序.
	Order OptListExecutionOrder `json:",omitempty,omitzero"`
	// Workflow ID.
	ID string
}

// ListExecutionHistoryParams is parameters of listExecutionHistory operation.
type ListExecutionHistoryParams struct {
	// ページ番号.
	Page OptInt `json:",omitempty,omitzero"`
	// 1ページあたりのリソースの取得数.
	PageLimit OptInt `json:",omitempty,omitzero"`
	// ソートの順序.
	SortOrder OptListExecutionHistorySortOrder `json:",omitempty,omitzero"`
	// Workflow ID.
	ID string
	// Execution ID.
	ExecutionId string
}

// ListWorkflowParams is parameters of listWorkflow operation.
type ListWorkflowParams struct {
	// ページ番号.
	Page OptInt `json:",omitempty,omitzero"`
	// 1ページあたりのリソースの取得数.
	PageLimit OptInt `json:",omitempty,omitzero"`
	// Workflowのソートに利用するプロパティ.
	SortBy OptListWorkflowSortBy `json:",omitempty,omitzero"`
	// ソートの順序.
	Order OptListWorkflowOrder `json:",omitempty,omitzero"`
	// 公開状態の絞り込み.
	Published OptBool `json:",omitempty,omitzero"`
	// ワークフロー名の絞り込み.
	Name OptString `json:",omitempty,omitzero"`
	// ワークフロー名の絞り込み方法.
	NameMatchType OptListWorkflowNameMatchType `json:",omitempty,omitzero"`
}

// ListWorkflowRevisionsParams is parameters of listWorkflowRevisions operation.
type ListWorkflowRevisionsParams struct {
	// ページ番号.
	Page OptInt `json:",omitempty,omitzero"`
	// 1ページあたりのリソースの取得数.
	PageLimit OptInt `json:",omitempty,omitzero"`
	// Workflowのソートに利用するプロパティ.
	SortBy OptListWorkflowRevisionsSortBy `json:",omitempty,omitzero"`
	// ソートの順序.
	Order OptListWorkflowRevisionsOrder `json:",omitempty,omitzero"`
	// 公開状態の絞り込み.
	Published OptBool `json:",omitempty,omitzero"`
	// Workflow ID.
	ID string
}

// UpdateWorkflowParams is parameters of updateWorkflow operation.
type UpdateWorkflowParams struct {
	// Workflow ID.
	ID string
}

// UpdateWorkflowRevisionAliasParams is parameters of updateWorkflowRevisionAlias operation.
type UpdateWorkflowRevisionAliasParams struct {
	// Workflow ID.
	ID string
	// Revision ID.
	RevisionId float64
}
