// Code generated by ogen, DO NOT EDIT.
package v1

type CancelExecutionRes interface {
	cancelExecutionRes()
}

type CreateExecutionRes interface {
	createExecutionRes()
}

type CreateWorkflowRes interface {
	createWorkflowRes()
}

type CreateWorkflowRevisionRes interface {
	createWorkflowRevisionRes()
}

type DeleteExecutionRes interface {
	deleteExecutionRes()
}

type DeleteWorkflowRes interface {
	deleteWorkflowRes()
}

type DeleteWorkflowRevisionAliasRes interface {
	deleteWorkflowRevisionAliasRes()
}

type GetExecutionRes interface {
	getExecutionRes()
}

type GetWorkflowRes interface {
	getWorkflowRes()
}

type GetWorkflowRevisionsRes interface {
	getWorkflowRevisionsRes()
}

type ListExecutionHistoryRes interface {
	listExecutionHistoryRes()
}

type ListExecutionRes interface {
	listExecutionRes()
}

type ListWorkflowRes interface {
	listWorkflowRes()
}

type ListWorkflowRevisionsRes interface {
	listWorkflowRevisionsRes()
}

type UpdateWorkflowRes interface {
	updateWorkflowRes()
}

type UpdateWorkflowRevisionAliasRes interface {
	updateWorkflowRevisionAliasRes()
}
