// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"time"
)

// SetFake set fake values.
func (s *CancelExecutionAccepted) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Execution.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CancelExecutionAcceptedExecution) SetFake() {
	{
		{
			s.ExecutionId = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Workflow.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.Revision = float64(0)
		}
	}
	{
		{
			s.RevisionAlias = "string"
		}
	}
	{
		{
			s.Args = "string"
		}
	}
	{
		{
			s.Result = "string"
		}
	}
	{
		{
			s.Error = "string"
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
	{
		{
			s.RunAt.SetFake()
		}
	}
	{
		{
			s.FailedAt.SetFake()
		}
	}
	{
		{
			s.SucceededAt.SetFake()
		}
	}
	{
		{
			s.CancelRequestedAt.SetFake()
		}
	}
	{
		{
			s.CanceledAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CancelExecutionAcceptedExecutionStatus) SetFake() {
	*s = CancelExecutionAcceptedExecutionStatusQueued
}

// SetFake set fake values.
func (s *CancelExecutionAcceptedExecutionWorkflow) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Publish = true
		}
	}
	{
		{
			s.Logging = true
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem CancelExecutionAcceptedExecutionWorkflowTagsItem
				{
					elem.SetFake()
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.ServicePrincipalId.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *CancelExecutionAcceptedExecutionWorkflowServicePrincipalId) SetFake() {
	var variant string

	{
		variant = "string"
	}
	s.SetString(variant)
}

// SetFake set fake values.
func (s *CancelExecutionAcceptedExecutionWorkflowTagsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
}

// SetFake set fake values.
func (s *CancelExecutionBadRequest) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CancelExecutionForbidden) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CancelExecutionInternalServerError) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CancelExecutionNotFound) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CancelExecutionUnauthorized) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateExecutionBadRequest) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateExecutionCreated) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Execution.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateExecutionCreatedExecution) SetFake() {
	{
		{
			s.ExecutionId = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Workflow.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.Revision = float64(0)
		}
	}
	{
		{
			s.RevisionAlias = "string"
		}
	}
	{
		{
			s.Args = "string"
		}
	}
	{
		{
			s.Result = "string"
		}
	}
	{
		{
			s.Error = "string"
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
	{
		{
			s.RunAt.SetFake()
		}
	}
	{
		{
			s.FailedAt.SetFake()
		}
	}
	{
		{
			s.SucceededAt.SetFake()
		}
	}
	{
		{
			s.CancelRequestedAt.SetFake()
		}
	}
	{
		{
			s.CanceledAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateExecutionCreatedExecutionStatus) SetFake() {
	*s = CreateExecutionCreatedExecutionStatusQueued
}

// SetFake set fake values.
func (s *CreateExecutionCreatedExecutionWorkflow) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Publish = true
		}
	}
	{
		{
			s.Logging = true
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem CreateExecutionCreatedExecutionWorkflowTagsItem
				{
					elem.SetFake()
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.ServicePrincipalId.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *CreateExecutionCreatedExecutionWorkflowServicePrincipalId) SetFake() {
	var variant string

	{
		variant = "string"
	}
	s.SetString(variant)
}

// SetFake set fake values.
func (s *CreateExecutionCreatedExecutionWorkflowTagsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateExecutionForbidden) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateExecutionInternalServerError) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateExecutionNotFound) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateExecutionReq) SetFake() {
	{
		{
			s.RevisionId.SetFake()
		}
	}
	{
		{
			s.RevisionAlias.SetFake()
		}
	}
	{
		{
			s.Args.SetFake()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateExecutionUnauthorized) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateWorkflowBadRequest) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateWorkflowCreated) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Workflow.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateWorkflowCreatedWorkflow) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Publish = true
		}
	}
	{
		{
			s.Logging = true
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem CreateWorkflowCreatedWorkflowTagsItem
				{
					elem.SetFake()
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.ServicePrincipalId.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *CreateWorkflowCreatedWorkflowServicePrincipalId) SetFake() {
	var variant string

	{
		variant = "string"
	}
	s.SetString(variant)
}

// SetFake set fake values.
func (s *CreateWorkflowCreatedWorkflowTagsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateWorkflowForbidden) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateWorkflowInternalServerError) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateWorkflowNotFound) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateWorkflowReq) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Runbook = "string"
		}
	}
	{
		{
			s.Publish = true
		}
	}
	{
		{
			s.Logging = true
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem CreateWorkflowReqTagsItem
				{
					elem.SetFake()
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.RevisionAlias.SetFake()
		}
	}
	{
		{
			s.ServicePrincipalId.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateWorkflowReqServicePrincipalId) SetFake() {
	var variant string

	{
		variant = "string"
	}
	s.SetString(variant)
}

// SetFake set fake values.
func (s *CreateWorkflowReqTagsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateWorkflowRevisionBadRequest) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateWorkflowRevisionCreated) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Revision.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateWorkflowRevisionCreatedRevision) SetFake() {
	{
		{
			s.RevisionId = float64(0)
		}
	}
	{
		{
			s.WorkflowId = "string"
		}
	}
	{
		{
			s.RevisionAlias.SetFake()
		}
	}
	{
		{
			s.Runbook = "string"
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *CreateWorkflowRevisionForbidden) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateWorkflowRevisionInternalServerError) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateWorkflowRevisionNotFound) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateWorkflowRevisionReq) SetFake() {
	{
		{
			s.Runbook = "string"
		}
	}
	{
		{
			s.RevisionAlias.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateWorkflowRevisionUnauthorized) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateWorkflowUnauthorized) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *DeleteExecutionBadRequest) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *DeleteExecutionForbidden) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *DeleteExecutionInternalServerError) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *DeleteExecutionNotFound) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *DeleteExecutionOK) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *DeleteExecutionUnauthorized) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *DeleteWorkflowBadRequest) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *DeleteWorkflowForbidden) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *DeleteWorkflowInternalServerError) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *DeleteWorkflowNotFound) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *DeleteWorkflowOK) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *DeleteWorkflowRevisionAliasBadRequest) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *DeleteWorkflowRevisionAliasForbidden) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *DeleteWorkflowRevisionAliasInternalServerError) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *DeleteWorkflowRevisionAliasNotFound) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *DeleteWorkflowRevisionAliasOK) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Workflow.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *DeleteWorkflowRevisionAliasOKWorkflow) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Publish = true
		}
	}
	{
		{
			s.Logging = true
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem DeleteWorkflowRevisionAliasOKWorkflowTagsItem
				{
					elem.SetFake()
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.ServicePrincipalId.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *DeleteWorkflowRevisionAliasOKWorkflowServicePrincipalId) SetFake() {
	var variant string

	{
		variant = "string"
	}
	s.SetString(variant)
}

// SetFake set fake values.
func (s *DeleteWorkflowRevisionAliasOKWorkflowTagsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
}

// SetFake set fake values.
func (s *DeleteWorkflowRevisionAliasUnauthorized) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *DeleteWorkflowUnauthorized) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetExecutionBadRequest) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetExecutionForbidden) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetExecutionInternalServerError) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetExecutionNotFound) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetExecutionOK) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Execution.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetExecutionOKExecution) SetFake() {
	{
		{
			s.ExecutionId = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Workflow.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.Revision = float64(0)
		}
	}
	{
		{
			s.RevisionAlias = "string"
		}
	}
	{
		{
			s.Args = "string"
		}
	}
	{
		{
			s.Result = "string"
		}
	}
	{
		{
			s.Error = "string"
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
	{
		{
			s.RunAt.SetFake()
		}
	}
	{
		{
			s.FailedAt.SetFake()
		}
	}
	{
		{
			s.SucceededAt.SetFake()
		}
	}
	{
		{
			s.CancelRequestedAt.SetFake()
		}
	}
	{
		{
			s.CanceledAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetExecutionOKExecutionStatus) SetFake() {
	*s = GetExecutionOKExecutionStatusQueued
}

// SetFake set fake values.
func (s *GetExecutionOKExecutionWorkflow) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Publish = true
		}
	}
	{
		{
			s.Logging = true
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem GetExecutionOKExecutionWorkflowTagsItem
				{
					elem.SetFake()
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.ServicePrincipalId.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *GetExecutionOKExecutionWorkflowServicePrincipalId) SetFake() {
	var variant string

	{
		variant = "string"
	}
	s.SetString(variant)
}

// SetFake set fake values.
func (s *GetExecutionOKExecutionWorkflowTagsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetExecutionUnauthorized) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetWorkflowBadRequest) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetWorkflowForbidden) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetWorkflowInternalServerError) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetWorkflowNotFound) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetWorkflowOK) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Workflow.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetWorkflowOKWorkflow) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Publish = true
		}
	}
	{
		{
			s.Logging = true
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem GetWorkflowOKWorkflowTagsItem
				{
					elem.SetFake()
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.ServicePrincipalId.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *GetWorkflowOKWorkflowServicePrincipalId) SetFake() {
	var variant string

	{
		variant = "string"
	}
	s.SetString(variant)
}

// SetFake set fake values.
func (s *GetWorkflowOKWorkflowTagsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetWorkflowRevisionsBadRequest) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetWorkflowRevisionsForbidden) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetWorkflowRevisionsInternalServerError) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetWorkflowRevisionsNotFound) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetWorkflowRevisionsOK) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Revision.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetWorkflowRevisionsOKRevision) SetFake() {
	{
		{
			s.RevisionId = float64(0)
		}
	}
	{
		{
			s.WorkflowId = "string"
		}
	}
	{
		{
			s.RevisionAlias.SetFake()
		}
	}
	{
		{
			s.Runbook = "string"
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *GetWorkflowRevisionsUnauthorized) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetWorkflowUnauthorized) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListExecutionBadRequest) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListExecutionForbidden) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListExecutionHistoryBadRequest) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListExecutionHistoryForbidden) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListExecutionHistoryInternalServerError) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListExecutionHistoryNotFound) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListExecutionHistoryOK) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Total = int(0)
		}
	}
	{
		{
			s.From = int(0)
		}
	}
	{
		{
			s.Count = int(0)
		}
	}
	{
		{
			s.Histories = nil
			for i := 0; i < 0; i++ {
				var elem ListExecutionHistoryOKHistoriesItem
				{
					elem.SetFake()
				}
				s.Histories = append(s.Histories, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ListExecutionHistoryOKHistoriesItem) SetFake() {
	{
		{
			s.WorkflowExecutionId = "string"
		}
	}
	{
		{
			s.JobId = "string"
		}
	}
	{
		{
			s.ThreadId = "string"
		}
	}
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.Meta = "string"
		}
	}
	{
		{
			s.StackTrace = "string"
		}
	}
	{
		{
			s.Variables = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListExecutionHistoryOKHistoriesItemType) SetFake() {
	*s = ListExecutionHistoryOKHistoriesItemTypeWorkflowWillStart
}

// SetFake set fake values.
func (s *ListExecutionHistoryUnauthorized) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListExecutionInternalServerError) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListExecutionNotFound) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListExecutionOK) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Total = int(0)
		}
	}
	{
		{
			s.From = int(0)
		}
	}
	{
		{
			s.Count = int(0)
		}
	}
	{
		{
			s.Executions = nil
			for i := 0; i < 0; i++ {
				var elem ListExecutionOKExecutionsItem
				{
					elem.SetFake()
				}
				s.Executions = append(s.Executions, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ListExecutionOKExecutionsItem) SetFake() {
	{
		{
			s.ExecutionId = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Workflow.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.Revision = float64(0)
		}
	}
	{
		{
			s.RevisionAlias = "string"
		}
	}
	{
		{
			s.Args = "string"
		}
	}
	{
		{
			s.Result = "string"
		}
	}
	{
		{
			s.Error = "string"
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
	{
		{
			s.RunAt.SetFake()
		}
	}
	{
		{
			s.FailedAt.SetFake()
		}
	}
	{
		{
			s.SucceededAt.SetFake()
		}
	}
	{
		{
			s.CancelRequestedAt.SetFake()
		}
	}
	{
		{
			s.CanceledAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ListExecutionOKExecutionsItemStatus) SetFake() {
	*s = ListExecutionOKExecutionsItemStatusQueued
}

// SetFake set fake values.
func (s *ListExecutionOKExecutionsItemWorkflow) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Publish = true
		}
	}
	{
		{
			s.Logging = true
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem ListExecutionOKExecutionsItemWorkflowTagsItem
				{
					elem.SetFake()
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.ServicePrincipalId.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *ListExecutionOKExecutionsItemWorkflowServicePrincipalId) SetFake() {
	var variant string

	{
		variant = "string"
	}
	s.SetString(variant)
}

// SetFake set fake values.
func (s *ListExecutionOKExecutionsItemWorkflowTagsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListExecutionUnauthorized) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListWorkflowBadRequest) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListWorkflowForbidden) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListWorkflowInternalServerError) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListWorkflowNotFound) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListWorkflowOK) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Total = int(0)
		}
	}
	{
		{
			s.From = int(0)
		}
	}
	{
		{
			s.Count = int(0)
		}
	}
	{
		{
			s.Workflows = nil
			for i := 0; i < 0; i++ {
				var elem ListWorkflowOKWorkflowsItem
				{
					elem.SetFake()
				}
				s.Workflows = append(s.Workflows, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ListWorkflowOKWorkflowsItem) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Publish = true
		}
	}
	{
		{
			s.Logging = true
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem ListWorkflowOKWorkflowsItemTagsItem
				{
					elem.SetFake()
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.ServicePrincipalId.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *ListWorkflowOKWorkflowsItemServicePrincipalId) SetFake() {
	var variant string

	{
		variant = "string"
	}
	s.SetString(variant)
}

// SetFake set fake values.
func (s *ListWorkflowOKWorkflowsItemTagsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListWorkflowRevisionsBadRequest) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListWorkflowRevisionsForbidden) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListWorkflowRevisionsInternalServerError) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListWorkflowRevisionsNotFound) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListWorkflowRevisionsOK) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Total = int(0)
		}
	}
	{
		{
			s.From = int(0)
		}
	}
	{
		{
			s.Count = int(0)
		}
	}
	{
		{
			s.Revisions = nil
			for i := 0; i < 0; i++ {
				var elem ListWorkflowRevisionsOKRevisionsItem
				{
					elem.SetFake()
				}
				s.Revisions = append(s.Revisions, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ListWorkflowRevisionsOKRevisionsItem) SetFake() {
	{
		{
			s.RevisionId = float64(0)
		}
	}
	{
		{
			s.WorkflowId = "string"
		}
	}
	{
		{
			s.RevisionAlias.SetFake()
		}
	}
	{
		{
			s.Runbook = "string"
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *ListWorkflowRevisionsUnauthorized) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ListWorkflowUnauthorized) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *OptBool) SetFake() {
	var elem bool
	{
		elem = true
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCancelExecutionAcceptedExecutionWorkflowServicePrincipalId) SetFake() {
	var elem CancelExecutionAcceptedExecutionWorkflowServicePrincipalId
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCreateExecutionCreatedExecutionWorkflowServicePrincipalId) SetFake() {
	var elem CreateExecutionCreatedExecutionWorkflowServicePrincipalId
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCreateExecutionReq) SetFake() {
	var elem CreateExecutionReq
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCreateWorkflowCreatedWorkflowServicePrincipalId) SetFake() {
	var elem CreateWorkflowCreatedWorkflowServicePrincipalId
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCreateWorkflowReq) SetFake() {
	var elem CreateWorkflowReq
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCreateWorkflowReqServicePrincipalId) SetFake() {
	var elem CreateWorkflowReqServicePrincipalId
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCreateWorkflowRevisionReq) SetFake() {
	var elem CreateWorkflowRevisionReq
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptDateTime) SetFake() {
	var elem time.Time
	{
		elem = time.Now()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptDeleteWorkflowRevisionAliasOKWorkflowServicePrincipalId) SetFake() {
	var elem DeleteWorkflowRevisionAliasOKWorkflowServicePrincipalId
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptFloat64) SetFake() {
	var elem float64
	{
		elem = float64(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptGetExecutionOKExecutionWorkflowServicePrincipalId) SetFake() {
	var elem GetExecutionOKExecutionWorkflowServicePrincipalId
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptGetWorkflowOKWorkflowServicePrincipalId) SetFake() {
	var elem GetWorkflowOKWorkflowServicePrincipalId
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptListExecutionOKExecutionsItemWorkflowServicePrincipalId) SetFake() {
	var elem ListExecutionOKExecutionsItemWorkflowServicePrincipalId
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptListWorkflowOKWorkflowsItemServicePrincipalId) SetFake() {
	var elem ListWorkflowOKWorkflowsItemServicePrincipalId
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptString) SetFake() {
	var elem string
	{
		elem = "string"
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptUpdateWorkflowOKWorkflowServicePrincipalId) SetFake() {
	var elem UpdateWorkflowOKWorkflowServicePrincipalId
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptUpdateWorkflowReq) SetFake() {
	var elem UpdateWorkflowReq
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptUpdateWorkflowRevisionAliasReq) SetFake() {
	var elem UpdateWorkflowRevisionAliasReq
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *UpdateWorkflowBadRequest) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *UpdateWorkflowForbidden) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *UpdateWorkflowInternalServerError) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *UpdateWorkflowNotFound) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *UpdateWorkflowOK) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Workflow.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *UpdateWorkflowOKWorkflow) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Publish = true
		}
	}
	{
		{
			s.Logging = true
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem UpdateWorkflowOKWorkflowTagsItem
				{
					elem.SetFake()
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.ServicePrincipalId.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *UpdateWorkflowOKWorkflowServicePrincipalId) SetFake() {
	var variant string

	{
		variant = "string"
	}
	s.SetString(variant)
}

// SetFake set fake values.
func (s *UpdateWorkflowOKWorkflowTagsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
}

// SetFake set fake values.
func (s *UpdateWorkflowReq) SetFake() {
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Publish.SetFake()
		}
	}
	{
		{
			s.Logging.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem UpdateWorkflowReqTagsItem
				{
					elem.SetFake()
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *UpdateWorkflowReqTagsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
}

// SetFake set fake values.
func (s *UpdateWorkflowRevisionAliasBadRequest) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *UpdateWorkflowRevisionAliasForbidden) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *UpdateWorkflowRevisionAliasInternalServerError) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *UpdateWorkflowRevisionAliasNotFound) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *UpdateWorkflowRevisionAliasOK) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Revision.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *UpdateWorkflowRevisionAliasOKRevision) SetFake() {
	{
		{
			s.RevisionId = float64(0)
		}
	}
	{
		{
			s.WorkflowId = "string"
		}
	}
	{
		{
			s.RevisionAlias.SetFake()
		}
	}
	{
		{
			s.Runbook = "string"
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *UpdateWorkflowRevisionAliasReq) SetFake() {
	{
		{
			s.RevisionAlias = "string"
		}
	}
}

// SetFake set fake values.
func (s *UpdateWorkflowRevisionAliasUnauthorized) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *UpdateWorkflowUnauthorized) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}
