// Code generated by ogen, DO NOT EDIT.

package v1

// setDefaults set default value of fields.
func (s *CancelExecutionAcceptedExecution) setDefaults() {
	{
		val := int(0)
		s.StepCount = val
	}
}

// setDefaults set default value of fields.
func (s *CancelExecutionBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CancelExecutionConflict) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CancelExecutionForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CancelExecutionInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CancelExecutionNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CancelExecutionOKExecution) setDefaults() {
	{
		val := int(0)
		s.StepCount = val
	}
}

// setDefaults set default value of fields.
func (s *CancelExecutionPaymentRequired) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CancelExecutionUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateExecutionBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateExecutionConflict) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateExecutionCreatedExecution) setDefaults() {
	{
		val := int(0)
		s.StepCount = val
	}
}

// setDefaults set default value of fields.
func (s *CreateExecutionForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateExecutionInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateExecutionNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateExecutionPaymentRequired) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateExecutionUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateSubscriptionBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateSubscriptionForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateSubscriptionInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateSubscriptionNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateSubscriptionUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateWorkflowBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateWorkflowForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateWorkflowInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateWorkflowNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateWorkflowPaymentRequired) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateWorkflowRevisionBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateWorkflowRevisionConflict) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateWorkflowRevisionForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateWorkflowRevisionInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateWorkflowRevisionNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateWorkflowRevisionPaymentRequired) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateWorkflowRevisionUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *CreateWorkflowUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteExecutionBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteExecutionConflict) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteExecutionForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteExecutionInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteExecutionNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteExecutionPaymentRequired) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteExecutionUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteSubscriptionBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteSubscriptionForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteSubscriptionInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteSubscriptionNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteSubscriptionUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteWorkflowBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteWorkflowConflict) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteWorkflowForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteWorkflowInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteWorkflowNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteWorkflowPaymentRequired) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteWorkflowRevisionAliasBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteWorkflowRevisionAliasForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteWorkflowRevisionAliasInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteWorkflowRevisionAliasNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteWorkflowRevisionAliasPaymentRequired) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteWorkflowRevisionAliasUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *DeleteWorkflowUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetExecutionBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetExecutionForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetExecutionInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetExecutionNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetExecutionOKExecution) setDefaults() {
	{
		val := int(0)
		s.StepCount = val
	}
}

// setDefaults set default value of fields.
func (s *GetExecutionPaymentRequired) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetExecutionUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetSubscriptionBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetSubscriptionForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetSubscriptionInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetSubscriptionNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetSubscriptionUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetWorkflowBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetWorkflowForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetWorkflowInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetWorkflowNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetWorkflowPaymentRequired) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetWorkflowRevisionsBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetWorkflowRevisionsForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetWorkflowRevisionsInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetWorkflowRevisionsNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetWorkflowRevisionsPaymentRequired) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetWorkflowRevisionsUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *GetWorkflowUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListExecutionBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListExecutionForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListExecutionHistoryBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListExecutionHistoryForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListExecutionHistoryInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListExecutionHistoryNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListExecutionHistoryOK) setDefaults() {
	{
		val := int(0)
		s.Total = val
	}
	{
		val := int(0)
		s.From = val
	}
	{
		val := int(0)
		s.Count = val
	}
}

// setDefaults set default value of fields.
func (s *ListExecutionHistoryPaymentRequired) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListExecutionHistoryUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListExecutionInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListExecutionNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListExecutionOK) setDefaults() {
	{
		val := int(0)
		s.Total = val
	}
	{
		val := int(0)
		s.From = val
	}
	{
		val := int(0)
		s.Count = val
	}
}

// setDefaults set default value of fields.
func (s *ListExecutionOKExecutionsItem) setDefaults() {
	{
		val := int(0)
		s.StepCount = val
	}
}

// setDefaults set default value of fields.
func (s *ListExecutionPaymentRequired) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListExecutionUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListPlansBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListPlansForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListPlansInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListPlansNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListPlansOK) setDefaults() {
	{
		val := int(10)
		s.TaxRate = val
	}
}

// setDefaults set default value of fields.
func (s *ListPlansUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowOK) setDefaults() {
	{
		val := int(0)
		s.Total = val
	}
	{
		val := int(0)
		s.From = val
	}
	{
		val := int(0)
		s.Count = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowPaymentRequired) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowRevisionsBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowRevisionsForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowRevisionsInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowRevisionsNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowRevisionsOK) setDefaults() {
	{
		val := int(0)
		s.Total = val
	}
	{
		val := int(0)
		s.From = val
	}
	{
		val := int(0)
		s.Count = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowRevisionsPaymentRequired) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowRevisionsUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowSuggestBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowSuggestForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowSuggestInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowSuggestNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowSuggestOK) setDefaults() {
	{
		val := int(0)
		s.Total = val
	}
	{
		val := int(0)
		s.From = val
	}
	{
		val := int(0)
		s.Count = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowSuggestPaymentRequired) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowSuggestUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *ListWorkflowUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *UpdateWorkflowBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *UpdateWorkflowForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *UpdateWorkflowInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *UpdateWorkflowNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *UpdateWorkflowPaymentRequired) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *UpdateWorkflowRevisionAliasBadRequest) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *UpdateWorkflowRevisionAliasConflict) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *UpdateWorkflowRevisionAliasForbidden) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *UpdateWorkflowRevisionAliasInternalServerError) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *UpdateWorkflowRevisionAliasNotFound) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *UpdateWorkflowRevisionAliasPaymentRequired) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *UpdateWorkflowRevisionAliasUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}

// setDefaults set default value of fields.
func (s *UpdateWorkflowUnauthorized) setDefaults() {
	{
		val := bool(false)
		s.IsOk = val
	}
}
