// Code generated by ogen, DO NOT EDIT.

package v1

// OperationName is the ogen operation name
type OperationName = string

const (
	CancelExecutionOperation             OperationName = "CancelExecution"
	CreateExecutionOperation             OperationName = "CreateExecution"
	CreateWorkflowOperation              OperationName = "CreateWorkflow"
	CreateWorkflowRevisionOperation      OperationName = "CreateWorkflowRevision"
	DeleteExecutionOperation             OperationName = "DeleteExecution"
	DeleteWorkflowOperation              OperationName = "DeleteWorkflow"
	DeleteWorkflowRevisionAliasOperation OperationName = "DeleteWorkflowRevisionAlias"
	GetExecutionOperation                OperationName = "GetExecution"
	GetWorkflowOperation                 OperationName = "GetWorkflow"
	GetWorkflowRevisionsOperation        OperationName = "GetWorkflowRevisions"
	ListExecutionOperation               OperationName = "ListExecution"
	ListExecutionHistoryOperation        OperationName = "ListExecutionHistory"
	ListWorkflowOperation                OperationName = "ListWorkflow"
	ListWorkflowRevisionsOperation       OperationName = "ListWorkflowRevisions"
	UpdateWorkflowOperation              OperationName = "UpdateWorkflow"
	UpdateWorkflowRevisionAliasOperation OperationName = "UpdateWorkflowRevisionAlias"
)
